#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun  1 09:38:16 2020

@author: detlef
"""

class BaseClassMSG:
    def __init__(self, parent):
        self.parent = parent
        pass
    
    def process_msg(self, msg):
        self.msg_from_parent(msg)
        if self.parent is not None:
            self.parent.process_msg(msg)
    
    # overwrite
    # remove the messages from msg, which are handled, the rest is kept
    def msg_from_parent(self, msg):
        pass
